// frontend/vue-app/src/components/ai/PendingActionCard.vue
<script setup lang="ts">
import type { PendingActionCardModel, PendingActionConstraint } from '@/lib/ai/pendingActionDiff';
import UiButton from '../ui/UiButton.vue';
import UiPill from '../ui/UiPill.vue';

const props = withDefaults(defineProps<{
  action: PendingActionCardModel;
  busy?: boolean;
}>(), {
  busy: false,
});

const emit = defineEmits<{
  approve: [actionId: string];
  reject: [actionId: string];
}>();

function constraintText(item: PendingActionConstraint): string {
  return item.message ? `${item.name}: ${item.message}` : item.name;
}

function hardViolations() {
  return Array.isArray(props.action.hardViolations) ? props.action.hardViolations : [];
}
function softViolations() {
  return Array.isArray(props.action.softViolations) ? props.action.softViolations : [];
}
function diffRows() {
  return Array.isArray(props.action.diffRows) ? props.action.diffRows : [];
}
</script>

<template>
  <div class="pa-card" data-testid="pending-action-card">
    <div class="pa-header">
      <span class="pa-tool-name">{{ action.toolName || action.actionId }}</span>
      <UiPill v-if="action.irreversible" tone="danger">
        不可逆操作
      </UiPill>
      <UiPill v-if="hardViolations().length" tone="danger">
        硬约束违规
      </UiPill>
    </div>

    <p v-if="action.message" class="pa-alert is-warn">
      {{ action.message }}
    </p>

    <p v-if="action.objectType || action.objectId" class="pa-meta">
      对象: {{ action.objectType || 'Unknown' }} / {{ action.objectId || '-' }}
    </p>

    <div v-if="hardViolations().length" class="pa-alert is-danger">
      <div class="pa-alert-title">
        硬约束违规
      </div>
      <div v-for="(item, i) in hardViolations()" :key="`h_${i}`">
        {{ constraintText(item) }}
      </div>
    </div>

    <div v-if="softViolations().length" class="pa-alert is-warn">
      <div class="pa-alert-title">
        软约束提示
      </div>
      <div v-for="(item, i) in softViolations()" :key="`s_${i}`">
        {{ constraintText(item) }}
      </div>
    </div>

    <table v-if="diffRows().length" class="pa-diff">
      <thead>
        <tr><th>字段</th><th>变更前</th><th>变更后</th></tr>
      </thead>
      <tbody>
        <tr v-for="row in diffRows()" :key="row.field">
          <td class="pa-diff-field">
            {{ row.field }}
          </td>
          <td>{{ row.before }}</td>
          <td>{{ row.after }}</td>
        </tr>
      </tbody>
    </table>

    <p class="pa-meta">
      状态: {{ action.status || 'pending' }}
    </p>
    <p v-if="action.sourceRunId || action.sourceTool" class="pa-meta">
      来源: {{ [action.sourceTool, action.sourceRunId].filter(Boolean).join(' / ') }}
    </p>
    <p v-if="action.createdAt" class="pa-meta">
      创建: {{ action.createdAt }}
    </p>
    <p v-if="action.expiresAt" class="pa-meta">
      过期: {{ action.expiresAt }}
    </p>

    <div class="pa-actions">
      <UiButton
        class="is-approve"
        variant="primary"
        :disabled="busy"
        @click="emit('approve', action.actionId)"
      >
        批准
      </UiButton>
      <UiButton
        class="is-reject"
        variant="danger"
        :disabled="busy"
        @click="emit('reject', action.actionId)"
      >
        拒绝
      </UiButton>
    </div>
  </div>
</template>

<style scoped>
.pa-card {
  border: 1px solid var(--line);
  border-radius: var(--r-panel);
  background: var(--face-raised);
  padding: var(--s3);
  display: flex;
  flex-direction: column;
  gap: var(--s2);
}

.pa-header {
  display: flex;
  align-items: center;
  gap: var(--s2);
  flex-wrap: wrap;
}

.pa-tool-name {
  font-size: var(--fs-body);
  font-weight: var(--fw-semibold);
  color: var(--ink);
}

.pa-alert {
  margin: 0;
  padding: var(--s2) var(--s3);
  border-radius: var(--r-control);
  font-size: var(--fs-label);
  line-height: 1.5;
}

.pa-alert.is-warn {
  background: var(--warn-soft);
  color: var(--warn);
}

.pa-alert.is-danger {
  background: var(--danger-soft);
  color: var(--danger);
}

.pa-alert-title {
  font-weight: var(--fw-semibold);
  margin-bottom: 2px;
}

.pa-meta {
  margin: 0;
  font-size: var(--fs-label);
  color: var(--ink-subtle);
}

.pa-diff {
  width: 100%;
  border-collapse: collapse;
  font-size: var(--fs-label);
}

.pa-diff th {
  text-align: left;
  color: var(--ink-subtle);
  font-weight: var(--fw-medium);
  padding: var(--s1) var(--s2);
  border-bottom: 1px solid var(--line-strong);
}

.pa-diff td {
  padding: var(--s1) var(--s2);
  border-bottom: 1px solid var(--line);
  color: var(--ink);
  word-break: break-all;
}

.pa-diff-field {
  font-family: var(--mono);
  white-space: nowrap;
}

.pa-actions {
  display: flex;
  gap: var(--s2);
}
</style>

// frontend/ai-react/src/components/chat/PendingActionCard.tsx
import { Alert, Button, Card, Space, Table, Tag, Typography } from 'antd';
import type { PendingActionCardModel, PendingActionConstraint, PendingActionDiffRow } from '@/components/chat/pendingActionDiff';

export type { PendingActionCardModel } from '@/components/chat/pendingActionDiff';

function constraintText(item: PendingActionConstraint): string {
  return item.message ? `${item.name}: ${item.message}` : item.name;
}

export function PendingActionCard(props: {
  action: PendingActionCardModel;
  busy?: boolean;
  onApprove: (actionId: string) => Promise<void> | void;
  onReject: (actionId: string) => Promise<void> | void;
}): JSX.Element {
  const { action, busy = false, onApprove, onReject } = props;
  const hardViolations = Array.isArray(action.hardViolations) ? action.hardViolations : [];
  const softViolations = Array.isArray(action.softViolations) ? action.softViolations : [];
  const diffRows = Array.isArray(action.diffRows) ? action.diffRows : [];
  const hasHardViolations = hardViolations.length > 0;

  const diffColumns = [
    { title: '字段', dataIndex: 'field', key: 'field', width: 110 },
    { title: '变更前', dataIndex: 'before', key: 'before', ellipsis: true },
    { title: '变更后', dataIndex: 'after', key: 'after', ellipsis: true },
  ];

  return (
    <Card
      size="small"
      title={
        <Space size={6} wrap>
          <span>{action.toolName || action.actionId}</span>
          {action.irreversible ? <Tag color="red">不可逆操作</Tag> : null}
          {hasHardViolations ? <Tag color="red">硬约束违规</Tag> : null}
        </Space>
      }
    >
      <Space direction="vertical" style={{ width: '100%' }} size={8}>
        {action.message ? <Alert type="warning" message={action.message} showIcon /> : null}

        {action.objectType || action.objectId ? (
          <Typography.Text type="secondary">
            对象: {action.objectType || 'Unknown'} / {action.objectId || '-'}
          </Typography.Text>
        ) : null}

        {hardViolations.length > 0 ? (
          <Alert
            type="error"
            showIcon
            message="硬约束违规"
            description={
              <Space direction="vertical" size={2} style={{ width: '100%' }}>
                {hardViolations.map((item, index) => (
                  <span key={`${item.name}_${index}`}>{constraintText(item)}</span>
                ))}
              </Space>
            }
          />
        ) : null}

        {softViolations.length > 0 ? (
          <Alert
            type="warning"
            showIcon
            message="软约束提示"
            description={
              <Space direction="vertical" size={2} style={{ width: '100%' }}>
                {softViolations.map((item, index) => (
                  <span key={`${item.name}_${index}`}>{constraintText(item)}</span>
                ))}
              </Space>
            }
          />
        ) : null}

        {diffRows.length > 0 ? (
          <Table<PendingActionDiffRow>
            size="small"
            rowKey={(row) => row.field}
            columns={diffColumns}
            dataSource={diffRows}
            pagination={false}
            scroll={{ x: 'max-content' }}
          />
        ) : null}

        <Typography.Text type="secondary">状态: {action.status || 'pending'}</Typography.Text>
        {action.sourceRunId || action.sourceTool ? (
          <Typography.Text type="secondary">
            来源: {[action.sourceTool, action.sourceRunId].filter(Boolean).join(' / ')}
          </Typography.Text>
        ) : null}
        {action.createdAt ? <Typography.Text type="secondary">创建: {action.createdAt}</Typography.Text> : null}
        {action.expiresAt ? <Typography.Text type="secondary">过期: {action.expiresAt}</Typography.Text> : null}
        <Space>
          <Button
            type="primary"
            danger={hasHardViolations}
            loading={busy}
            onClick={() => onApprove(action.actionId)}
          >
            批准
          </Button>
          <Button danger loading={busy} onClick={() => onReject(action.actionId)}>
            拒绝
          </Button>
        </Space>
      </Space>
    </Card>
  );
}
